# Generated by Django 3.2.9 on 2023-06-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_guestuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=200, null=True)),
                ('word_count', models.CharField(max_length=200, null=True)),
                ('character_count', models.CharField(max_length=200, null=True)),
                ('typing_time', models.CharField(max_length=200, null=True)),
                ('inactive_time', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard.guestuser')),
            ],
        ),
    ]
