# Generated by Django 3.2.9 on 2023-06-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='pdf_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
    ]
