# Generated by Django 3.2.9 on 2023-06-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_auto_20230624_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typingTime', models.IntegerField()),
                ('inactiveTime', models.IntegerField()),
                ('wordCount', models.IntegerField()),
                ('charCount', models.IntegerField()),
            ],
        ),
    ]
